"""migración 1

Revision ID: 1f01f0ade401
Revises: 
Create Date: 2025-07-20 14:46:59.421273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f01f0ade401'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id_departamento', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_table('subproductos',
    sa.Column('id_subproducto', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('valor_adicion', sa.Float(precision=2), nullable=False),
    sa.Column('valor_remocion', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id_subproducto')
    )
    op.create_table('tipoComida',
    sa.Column('id_tipo_comida', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_comida')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('celular', sa.String(length=13), nullable=False),
    sa.Column('password', sa.String(length=13), nullable=False),
    sa.Column('usuario_verificado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tipo_usuario', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('municipio',
    sa.Column('id_municipio', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_departamento', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_table('orden',
    sa.Column('id_orden', sa.UUID(), nullable=False),
    sa.Column('precio_total', sa.Float(precision=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_table('restaurantes',
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rango_precios', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('tiempo_estimado', sa.Integer(), nullable=False),
    sa.Column('id_municipio', sa.UUID(), nullable=False),
    sa.Column('consumo_en_sitio', sa.Boolean(), nullable=False),
    sa.Column('delivery', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('opinionUsuarios',
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('cumple_tiempo_estimado', sa.Boolean(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurantes.id_restaurante'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_restaurante', 'id_usuario')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('imagen', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurantes.id_restaurante'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('restauranteTipoComida',
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('id_tipo_comida', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurantes.id_restaurante'], ),
    sa.ForeignKeyConstraint(['id_tipo_comida'], ['tipoComida.id_tipo_comida'], ),
    sa.PrimaryKeyConstraint('id_restaurante', 'id_tipo_comida')
    )
    op.create_table('ordenDetalles',
    sa.Column('id_orden_detalle', sa.UUID(), nullable=False),
    sa.Column('id_orden', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_orden_detalle')
    )
    op.create_table('productosSubproductos',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_subproducto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_subproducto'], ['subproductos.id_subproducto'], ),
    sa.PrimaryKeyConstraint('id_producto', 'id_subproducto')
    )
    op.create_table('ordenDetallePersonalizacion',
    sa.Column('id_orden_detalle_personalizacion', sa.UUID(), nullable=False),
    sa.Column('id_orden_detalle', sa.UUID(), nullable=False),
    sa.Column('id_subproducto', sa.UUID(), nullable=False),
    sa.Column('accion', sa.Integer(), nullable=False),
    sa.Column('ajuste_precio', sa.Float(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orden_detalle'], ['ordenDetalles.id_orden_detalle'], ),
    sa.ForeignKeyConstraint(['id_subproducto'], ['subproductos.id_subproducto'], ),
    sa.PrimaryKeyConstraint('id_orden_detalle_personalizacion')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenDetallePersonalizacion')
    op.drop_table('productosSubproductos')
    op.drop_table('ordenDetalles')
    op.drop_table('restauranteTipoComida')
    op.drop_table('productos')
    op.drop_table('opinionUsuarios')
    op.drop_table('restaurantes')
    op.drop_table('orden')
    op.drop_table('municipio')
    op.drop_table('usuarios')
    op.drop_table('tipoComida')
    op.drop_table('subproductos')
    op.drop_table('departamento')
    # ### end Alembic commands ###
