"""adding tables related subporducts

Revision ID: 2de7ee1b1274
Revises: 9818fa75e8fd
Create Date: 2025-07-11 19:37:21.046290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2de7ee1b1274'
down_revision = '9818fa75e8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productosSubproductos',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_subproducto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.ForeignKeyConstraint(['id_subproducto'], ['subproductos.id_subproducto'], ),
    sa.PrimaryKeyConstraint('id_producto', 'id_subproducto')
    )
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('ordenDetallePersonalizacion', schema=None) as batch_op:
        batch_op.alter_column('ajuste_precio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    with op.batch_alter_table('subproductos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('valor_adicion',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)
        batch_op.alter_column('valor_remocion',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subproductos', schema=None) as batch_op:
        batch_op.alter_column('valor_remocion',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('valor_adicion',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('ordenDetallePersonalizacion', schema=None) as batch_op:
        batch_op.alter_column('ajuste_precio',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('productosSubproductos')
    # ### end Alembic commands ###
