"""adding order table

Revision ID: 49f91de40b69
Revises: ad79c629654f
Create Date: 2025-07-10 17:47:49.269644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f91de40b69'
down_revision = 'ad79c629654f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden',
    sa.Column('id_orden', sa.UUID(), nullable=False),
    sa.Column('precio_total', sa.Float(precision=2), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular', sa.String(length=13), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=13), nullable=False))
        batch_op.add_column(sa.Column('usuario_verificado', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('usuario_verificado')
        batch_op.drop_column('password')
        batch_op.drop_column('celular')

    op.drop_table('orden')
    # ### end Alembic commands ###
