"""adding location tables

Revision ID: 8bc6f04313c0
Revises: 49f91de40b69
Create Date: 2025-07-11 16:57:02.277857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc6f04313c0'
down_revision = '49f91de40b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departamento',
    sa.Column('id_departamento', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_departamento')
    )
    op.create_table('ciudad',
    sa.Column('id_ciudad', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_departamento', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_departamento'], ['departamento.id_departamento'], ),
    sa.PrimaryKeyConstraint('id_ciudad')
    )
    op.create_table('municipio',
    sa.Column('id_municipio', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('id_ciudad', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_ciudad'], ['ciudad.id_ciudad'], ),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('municipio')
    op.drop_table('ciudad')
    op.drop_table('departamento')
    # ### end Alembic commands ###
