"""adding tables related to restaurant, orden and order details

Revision ID: 9818fa75e8fd
Revises: 8bc6f04313c0
Create Date: 2025-07-11 18:58:17.931803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9818fa75e8fd'
down_revision = '8bc6f04313c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subproductos',
    sa.Column('id_subproducto', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('valor_adicion', sa.Float(precision=2), nullable=False),
    sa.Column('valor_remocion', sa.Float(precision=2), nullable=False),
    sa.PrimaryKeyConstraint('id_subproducto')
    )
    op.create_table('restaurantes',
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('rango_precios', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('tiempo_estimado', sa.Integer(), nullable=False),
    sa.Column('id_municipio', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_municipio'], ['municipio.id_municipio'], ),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('precio', sa.Float(precision=2), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurantes.id_restaurante'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('restauranteTipoConsumo',
    sa.Column('id_restaurante', sa.UUID(), nullable=False),
    sa.Column('consumo_en_sitio', sa.Boolean(), nullable=False),
    sa.Column('delivery', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_restaurante'], ['restaurantes.id_restaurante'], ),
    sa.PrimaryKeyConstraint('id_restaurante')
    )
    op.create_table('ordenDetalles',
    sa.Column('id_orden_detalle', sa.UUID(), nullable=False),
    sa.Column('id_orden', sa.UUID(), nullable=False),
    sa.Column('id_producto', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id_orden'], ['orden.id_orden'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_orden_detalle')
    )
    op.create_table('ordenDetallePersonalizacion',
    sa.Column('id_orden_detalle_personalizacion', sa.UUID(), nullable=False),
    sa.Column('id_orden_detalle', sa.UUID(), nullable=False),
    sa.Column('id_subproducto', sa.UUID(), nullable=False),
    sa.Column('accion', sa.Integer(), nullable=False),
    sa.Column('ajuste_precio', sa.Float(precision=2), nullable=False),
    sa.ForeignKeyConstraint(['id_orden_detalle'], ['ordenDetalles.id_orden_detalle'], ),
    sa.ForeignKeyConstraint(['id_subproducto'], ['subproductos.id_subproducto'], ),
    sa.PrimaryKeyConstraint('id_orden_detalle_personalizacion')
    )
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('precio_total',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('ordenDetallePersonalizacion')
    op.drop_table('ordenDetalles')
    op.drop_table('restauranteTipoConsumo')
    op.drop_table('productos')
    op.drop_table('restaurantes')
    op.drop_table('subproductos')
    # ### end Alembic commands ###
